#!/usr/bin/env python3

#################################################################################
# h5edit
# 
# Copyright (C) 2022, Roshan J. Samuel
#
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     1. Redistributions of source code must retain the above copyright
#        notice, this list of conditions and the following disclaimer.
#     2. Redistributions in binary form must reproduce the above copyright
#        notice, this list of conditions and the following disclaimer in the
#        documentation and/or other materials provided with the distribution.
#     3. Neither the name of the copyright holder nor the
#        names of its contributors may be used to endorse or promote products
#        derived from this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#################################################################################

# Import all necessary modules
import numpy as np
import h5py as hp
import argparse

############################### MAIN FUNCTION ################################

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Edit HDF5 Files.')
    parser.add_argument('hd5file', metavar='f', type=ascii, nargs=1, help='input hdf5 file')
    parser.add_argument('-e', dest='edit', metavar=('attr', 'val'), nargs=2, help='edit attribute (attr) of hdf5 file to value (val)')
    parser.add_argument('-a', dest='add', metavar=('attr', 'val'), nargs=2, help='add attribute (attr) of hdf5 file to value (val)')
    parser.add_argument('-d', dest='delete', metavar=('attr'), nargs=1, help='delete attribute (attr) from the hdf5 file')
    args = parser.parse_args()

    print()

    # Open HDF5 file and get list of keys
    fileName = args.hd5file[0][1:-1]
    try:
        f = hp.File(fileName, 'r+')
    except:
        print("Could not open specified file.")
        exit()
    kList = list(f.keys())

    # Edit dataset
    if args.edit:
        editKey = args.edit[0]
        if editKey in kList:
            data = f[editKey]
            data[...] = np.float64(args.edit[1])
            f.close()
        else:
            print("Specified Key Not Found")
            exit()

    # Add dataset
    if args.add:
        addKey = args.add[0]
        f.create_dataset(addKey, data=np.float(args.add[1]))
        f.close()

    # Delete dataset
    if args.delete:
        delKey = args.delete[0]
        if delKey in kList:
            del f[delKey]
            f.close()
        else:
            print("Specified Key Not Found")
            exit()

